### ISSUE TITLE
Container image

### ISSUE THREAD

**Issue by micuentadecasa** [osisoft/sample-eds-eds_azure_deployment-shell#2]
Hi, I would like to test this code, but I don´t know how I can get the EDS Container image, neither their licensing, can you help me?

Regards.

**Comment by derekendres** [comment]
Hi,  I am sorry that we entirely missed this question.  We typically aren't looking in the Issues tab and instead ask people to either message the normal OSIsoft Technical Support or email us at samples@osisoft.com.  

If it is still relevant, the best way to get an EDS license would be to get you in touch with our sales team.  For the container image, we currently don't distribute a container image, but that might change moving forward.  Right now once you are licensed for it, you have access to an executable and instructions on how to create a docker container. https://docs.osisoft.com/bundle/edge-data-store/page/docker/edge-docker.html  

Again, apologies for not seeing this for almost a year.

**Comment by micuentadecasa** [comment]
Don't worry Derek, we have been busy with other projects. I will follow
your instructions.

Regards.
